class cmds: 
    hug = "Hugs the pinged person, kyoot!"
    snuggle = "Snuggles the pinged person, kyoot!"
    boop = "Boops the pinged person, boop!"
    kiss = "Smooches the pinged person :*"
    pat = "Pats the pinged person, good boy!"
    ping = "Displays the latency of the bo -connection lost"
    invite = "Displays the invite link to invite TPKP to your server"
    stats = "Shows some neat stats about TPKP"
    get_id = "Gets a users Discord ID"
    av = "Gets and posts avatar of the pinged person / ID works too"
    links = "Displays some links to get to The Paw Kingdom"
    random = "Can't make a choice? Use the random command! Only 2 options possible at this point"
    info = "You already know what this does, derp"

class syntax: 
    hug = "`?hug @user1 @user2..."
    snuggle = "?snuggle @user1 @user2..."
    boop = "?boop @user1 @user2..."
    kiss = "?kiss  @user1 @user2..."
    pat = "?pat  @user1 @user2...!"
    ping = "?ping"
    invite = "?invite"
    stats = "?stats"
    get_id = "?get_id @user"
    av = "?av @user / ID"
    links = "links"
    random = "?random choice1 choice2, if spaces, use \"these\"."
    info = "You already know what this does, derp"
